// Local-only lint config (see .gitignore) — ESLint is installed globally, not as a project dependency.
export default [
  {
    files: ["**/*.js"],
    ignores: ["node_modules/**", "dist/**", ".vite/**"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        console: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        performance: "readonly",
        self: "readonly",
        caches: "readonly",
        AudioContext: "readonly",
        webkitAudioContext: "readonly",
        URL: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-unreachable": "off",
      "no-const-assign": "error",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-duplicate-case": "error",
      "no-self-assign": "error",
      "no-fallthrough": "warn",
      "no-redeclare": "warn",
      "no-import-assign": "error",
      "no-setter-return": "error",
      "no-func-assign": "error",
      "no-obj-calls": "error",
      "valid-typeof": "error",
      "use-isnan": "error",
    },
  },
];
